---
title: "Gov 50 Final Project"
author: "Edona Cosovic"
description: "My final project for Gov 50"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

The central question I would like to investigate is: Do periods of increased immigration in New York City lead to increased arrests by the NYPD ? In this study, I plan to examine the extent to which periods in New York City history where the city has declared itself as a sanctuary city and the number of arrests made by the NYPD. I hypothesize that there is going to be an increased number of arrests made by the NYPD during these periods. During periods where New York City publicly reinstates their status as a sanctuary city, I expect that it is more likely for there to be a shift in public sentiment about the local government’s policy and thus more people committing crimes. During these periods, there might be fluctuations in crime because of this newfound sanctuary status made by the city. My sample is going to compromise of two samples that are anchored to two historical instances: first, during the 1980s, and second, amid the COVID-19 pandemic. Examining data from these specific time frames allows for a focused exploration of the relationship between sanctuary city status and the number of arrests made by the NYPD. 
The data I will retrieve is from the OpenDataNYC website where all of the data regarding arrests over time is included. For my analysis I will use the =1 for the designated times when the “sanctuary city” status was declared and =0 for the rest/not declared times. The outcome variable would be the amount of arrests made by the NYPD during each period. We will be able to see variation in comparing to the mean of the none sanctuary period arrests. By conducting a regression analysis of the amount of arrests made by te NYPD on the sanctuary city indicator variable for each of these periods, the results would give me insight on the impact of these declarations on law enforcement activities in NYC, and possibly support for my hypothesis. The pattern that would support my hypothesis is if there was a statistically significant increase in the number of arrests in this period. 

```{r}
library(ggplot2)
library(dplyr)
library(lubridate) 

arrests_data <- read.csv("NYPD_Arrest_Data__Year_to_Date__20231103.csv")
arrests_data$ARREST_DATE <- order(mdy(arrests_data$ARREST_DATE))

arrests_data <- read.csv("NYPD_Arrest_Data__Year_to_Date__20231103.csv")

arrests_data$Date <- as.Date(arrests_data$ARREST_DATE, format = "%m/%d/%Y")

arrests_data$Year <- format(arrests_data$Date, "%Y")
arrests_data$Month <- format(arrests_data$Date, "%m")

arrests_data_2023 <- filter(arrests_data, Year == "2023")

monthly_counts <- table(arrests_data_2023$Month)

monthly_counts_df <- data.frame(Month = as.character(names(monthly_counts)), Count = as.numeric(monthly_counts))

monthly_counts_df$Month <- factor(monthly_counts_df$Month, levels = sprintf("%02d", 1:12))

plot <- ggplot(data = monthly_counts_df, aes(x = Month, y = Count, group = 1)) +
  geom_line() +
  labs(title = "Number of Arrests Per Month in 2023", x = "Month", y = "Number of Arrests")
print(plot)
```






